config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[new create]

  resources :questions do
    resources :answers, expect: %i[new show]
  end

  root 'pages#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true, length: { minimum: 5 }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :email, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :set_question!
  before_action :set_answer!, except: :create

  def create
    @answer = @question.answers.build answer_params
    if @answer.save
      flash[:success] = 'Answer created'
      redirect_to question_path(@question)
    else
      @answers = @question.answers.order created_at: :desc
      render 'questions/show'
    end
  end

  def destroy
    if @answer.destroy
      flash[:success] = 'Answer deleted'
      redirect_to question_path(@question)
    else
      flash[:error] = 'Something went wrong'
    end
  end

  def edit
  end

  def update
    if @answer.update answer_params
      redirect_to question_path(@question, anchor: dom_id(@answer))
    else
      render :edit
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_question!
    @question = Question.find(params[:question_id])
  end
  def set_answer!
    @answer = Answer.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ErrorHandling
  include Pagy::Backend
  include Authentication
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    def current_user
      @current_user ||= User.find_by(id: session[:user_id]).decorate if session[:user_id].present?
    end

    def user_signed_in?
      current_user.present?
    end

    helper_method :current_user, :user_signed_in?
  end
end

app/controllers/concerns/current_user.rb
module CurrentUser
  extend ActiveSupport::Concern

  included do
    def current_user
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id].present?
    end

    def user_signed_in?
      current_user.present?
    end

    helper_method :current_user, :user_signed_in?
  end
end

app/controllers/concerns/error_handling.rb
module ErrorHandling
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound, with: :notfound

    private

    def notfound(exception)
      logger.warn exception
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index

  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question!, only: %i[show edit update destroy]

  def edit
  end

  def show
    @question = @question.decorate
    @answer = @question.answers.build
    @pagy, @answers = pagy(@question.answers.order(created_at: :desc), request_path: question_path)
    @answer = @answer.decorate

    # @answers = @question.answers.order(created_at: :desc).page(params[:page])
    # @answers = Answer.where(question: @question).order created_ad: :desc
  end

  def update
    if @question.update question_params
      flash[:success] = 'Question updated'
      redirect_to question_path
    else
      render :edit
    end
  end

  def destroy
    if @question.destroy
      flash[:success] = 'Question deleted'
      redirect_to questions_path
    else
      redirect_to questions_path
    end
  end

  def index
    @pagy, @questions = pagy(Question.order(created_at: :desc))
    @questions = @questions.decorate
    # @questions = Question.order(created_at: :desc).page params[:page]
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    if @question.save
      flash[:success] = 'Question created'
      redirect_to questions_path
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question!
    @question = Question.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the app, #{current_user.name_or_email}!"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def nav_tab(title, url, options = {})
    current_page = options.delete :current_page

    css_class = current_page == title ? 'text-secondary' : 'text-danger'

    options[:class] = if options[:class]
                        options[:class] + ' ' + css_class
                        # "#{options[:class]} #{css_class}"
                      else
                        css_class
                      end
    link_to title, url, options
  end

  def currently_at(current_page = '')
    render partial: 'shared/menu', locals: { current_page: current_page }
  end

  def full_title(page_title = '')
    base_title = 'AskMe'
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end
end

app/views/answers/_answer.html.erb
<%= tag.article class: 'card text-white bg-secondary mb-3', id: dom_id(answer) do %>
  <%# <article class = 'card text-white bg-secondary mb-3', id="answer-<%= answer.id%> <%# ">%>
    <div class = 'card-body'>
      <section class = 'card-text'>
        <time datetime="<%= answer.formated_created_at %>">
          <small><%= answer.formated_created_at %></small>
        </time>
        <div class = 'my-2'>
          <%= sanitize answer.body%>
        </div>
      </section>
      <%= link_to 'Delete', question_answer_path(question, answer), data:{turbo_method: :delete, turbo_confirm:'Are you sure?'}, class: 'btn btn-danger btn-sm'%>
      <%= link_to 'Edit', edit_question_answer_path(question, answer), class: 'btn btn-warning btn-sm'%>
    </div>
  </article>
<% end %>

app/views/answers/_form.html.erb
<%= render 'shared/errors', object: @answer %>

<%= form_with model: [@question, @answer], data:{turbo: false} do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, placeholder: 'Body', class: 'form-control' %>
    </div>
  </div>

  <%= f.submit "Submit answer!", class: 'btn btn-primary mb-3' %>

<% end %>

app/views/answers/edit.html.erb
<% provide :page_title, 'Edit Answer'%>
<% currently_at 'Answer' %>

<h1>Edit Answer</h1>

<%= render 'form'%>

app/views/layouts/application.html.erb
<!DOCTYPE html> 
<html>
  <head>
    <title><%= full_title(yield(:page_title)) %></title>
    <meta charset ="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%# <%= stylesheet_link_tag "style", media: 'all', "data-turbo-track": "reload" %>
    
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
  </head>

  <body>
    <%= yield :main_menu %>
    <main class = "container mt-3">
      <% flash.each do |k, v|%>
        <%# <div class = "alert alert-<%= k %> <%# ">
        <%#  <%= v %>
        <%#</div>%>
        <%= tag.div v, class: "alert alert-#{k}", role: "alert"%>
      <% end%>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<% currently_at 'Home' %>
<% provide :page_title %>

<h1>Welcome to AskMe</h1>

<%= current_user.inspect %>


&copy; @tuhtin <%= Time.now.year %>

app/views/questions/_form.html.erb
<%= render 'shared/errors', object: @question %>

<%= form_with model: @question, data:{turbo: false} do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
          <%= f.label :title%>
    </div>
    
    <div class="col-sm-10">
      <%= f.text_field :title, require: true, placeholder: 'Title', class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, placeholder: 'Body', class: 'form-control' %>
    </div>
  </div>

  <%= f.submit "Submit question!", class: 'btn btn-primary mb-3' %>

<% end %>

app/views/questions/edit.html.erb
<% provide :page_title, 'Edit Question'%>
<% currently_at 'Questions' %>

<h1 class = "mb-4">Edit Question</h1>

<%= render 'form' %>

<%= link_to 'Destroy', question_path(@question), class: 'btn btn-danger', data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>

app/views/questions/index.html.erb
<% provide :page_title, 'Questions' %>
<% currently_at 'Questions' %>

<h1 class="mb-4">Questions</h1>

<%= link_to 'New question', new_question_path, class: 'btn btn-primary btn-lg mb-3' %>

<%= raw (pagy_bootstrap_nav @pagy) if @pagy.pages > 1 %>

<%#<%= paginate @questions %>
<%== pagy_bootstrap_nav_js(@pagy) %>

<% @questions.each do |question| %>
  <article class="card mt-3 mb-3">
    <div class="card-body">
      <h4><%= question.title %></h2>

      <section class="card-text">
        <time datetime="<%= question.formated_created_at %>">
          <small><%= question.formated_created_at %></small>
        </time>

        <div class="my-2">
          <%= truncate (strip_tags question.body), length: 150, omission: '... (continued)' %>
        </div>
      </section>

      <%= link_to 'Show', question_path(question), class: 'btn btn-primary' %> 
      <%= link_to 'Edit', edit_question_path(question), class: 'btn btn-secondary' %>
      <%= link_to 'Destroy', question_path(question), class: 'btn btn-danger', data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
    </div>
  </article>
<% end %>

<%#<%= paginate @questions %>
<%= raw (pagy_bootstrap_nav @pagy) if @pagy.pages > 1 %>

app/views/questions/new.html.erb
<% provide :page_title, 'New Question' %>
<% currently_at 'Questions' %>

<h1 class="mb-4">New question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<% provide :page_title, 'Question with Answers'%>
<% currently_at 'Questions' %>

<h1 class="mb-4">Show question</h1>

<article class="card mb-3 mt-3">
  <div class="card-body">

    <h4><%= @question.title %></h2>
  
    <section class="card-text">
      <time datetime="<%= @question.formated_created_at %>">
        <small><%= @question.formated_created_at %></small>
      </time>
      <div class="my-2">
        <%= sanitize @question.body %>
      </div>
    </section>

    <%= link_to 'Back', questions_path(@question), class: 'btn btn-warning' %> 
    <%= link_to 'Edit', edit_question_path(@question), class: 'btn btn-secondary' %>
    <%= link_to 'Destroy', question_path(@question), class: 'btn btn-danger',
     data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
  </div>
</article>


<h2 class = 'mb-3 mt-5'>Write your answer</h2>

<%= render 'answers/form'%>

<h2 class = 'mb-3 mt-5'>Answers for this question</h2>


<%#== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
<%= render partial: 'answers/answer', collection: @answers, 
  as: :answer, locals: {question: @question}%>
<%#== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>

  <%# обязательно указать то это паршал и указать путь
    колеция для того, чтобы все отображалось по очереди
    as для того, чтобы указать название элементов в коллекции
    так же для того чтобы не было ошибок в других элементах программы при вызове
    делаем из question локальную переменную и задаем ей значение 
    с помощью метода locals
    не забывать "=" после скобки %>

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <div class = "alert alert-danger">
    <ul class = "mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<% provide :main_menu do%>
  <header class ='p-3 bg-dark text-white'>
    <div class = "container">
      <nav class = "d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class = "nav col-12 col-lg-auto me-lg-auto mb-2 justify-content mb-md-0">
          <li><%= nav_tab 'Home', root_path, class: 'nav-link px-2', current_page: current_page %></li>
          <li><%= nav_tab 'Questions', questions_path, class: 'nav-link px-2', current_page: current_page %></li>
          <li><%= nav_tab 'Routes', "/rails/info/routes", class: 'nav-link px-2'%></li>
        </ul>

        <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <% if user_signed_in? %>
            <li>
              <a class="nav-link px-2 text-danger" href="#">
                <%= current_user.name_or_email %>
              </a>
            </li>
          <% else %>
            <li><%= nav_tab 'Sing Up', new_user_path,
             class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
        </ul>

      </nav>
    </div>
  </header>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', object: @user %>

<%= form_with model: @user, data:{turbo: false} do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
          <%= f.label :email%>
    </div>
    
    <div class="col-sm-10">
      <%= f.email_field :email, require: true, placeholder: 'E-mail', class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :name %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :name, placeholder: 'Name', class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password %>
    </div>

    <div class="col-sm-10">
      <%= f.password_field :password, class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password_confirmation %>
    </div>

    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, class: 'form-control form-control-lg' %>
    </div>
  </div>


  <%= f.submit "Register!", class: 'btn btn-primary mb-3' %>

<% end %>

app/views/users/new.html.erb
<% provide :page_title, 'Registration' %>
<% currently_at 'Sing Up' %>

<h1 class = 'mb-4'>Registration</h1>

<%= render 'form' %>